### ISSUE TITLE
Can't play same sound with different clones

### ISSUE THREAD

**Issue by TheShovel** [TurboWarp/scratch-audio#1]
### Expected behavior

2 of the same sound should play at once.

### Actual behavior

Both sounds just stop playing, and any other clones with the same sound will not play that sound at all.

### Steps to reproduce

Create 2 clones with "Play sound until done", with the same sound in a forever loop.

### Operating system and browser

Linux (PopOS) Chromium

Video

https://user-images.githubusercontent.com/68913917/213871081-ca1f906b-49fd-44f3-99f9-b727cc507434.mp4

And this is what  the clones do 

![image](https://user-images.githubusercontent.com/68913917/213871105-13f38a2b-4c1d-4e38-9a21-0be38fefed69.png)

**Comment by GarboMuffin** [comment]
This seems like something that would make sense in an extension, especially since you seem to already be using extensions anyways

Follow https://github.com/TurboWarp/extensions/issues/163
